Repository openkim/kliff, pull requests merged in 2024-01, with the labels that each got.

#140 Fundamental changes to KIM models, transforms, and parameter classes
  kliff/models/__init__.py
  kliff/models/kim.py
  kliff/models/lennard_jones.py
  kliff/models/model.py
  kliff/models/parameter.py
  kliff/models/parameter_transform.py
  kliff/transforms/__init__.py
  kliff/transforms/parameter_transforms.py
  kliff/utils.py
  tests/models/test_kim.py
  tests/models/test_lennard_jones.py
  tests/models/test_parameter.py
  tests/models/test_parameter_transform.py
Labels: enhancement, feature

#156 Fix tests due to function name changes
  kliff/calculators/calculator.py
  kliff/loss.py
  tests/models/test_parameter.py
Labels: fix

#153 Added complete transform module for graph generation and
  README.md
  kliff/models/parameter.py
  kliff/transforms/configuration_transforms/__init__.py
  kliff/transforms/configuration_transforms/configuration_transform.py
  kliff/transforms/configuration_transforms/default_hyperparams.py
  kliff/transforms/configuration_transforms/descriptor_initializers.py
  kliff/transforms/configuration_transforms/descriptors.py
  kliff/transforms/configuration_transforms/graphs/__init__.py
  kliff/transforms/configuration_transforms/graphs/generate_graph.py
  kliff/transforms/configuration_transforms/graphs/kim_driver_graph_data.cpp
  kliff/transforms/configuration_transforms/graphs/periodic_table.hpp
  kliff/transforms/configuration_transforms/utils.py
  kliff/transforms/property_transforms.py
  kliff/utils.py
  setup.py
Labels: enhancement, feature

#157 Format using black 24.1.0
  .pre-commit-config.yaml
  examples/example_kim_SW_Si.py
  examples/example_lennard_jones.py
  examples/example_nn_Si.py
  examples/example_nn_SiC.py
  examples/example_parameter_transform.py
  examples/example_uq_bootstrap.py
  examples/example_uq_mcmc.py
  examples/legacy/eg_Fisher_info_kim_SW.py
Labels: enhancement
