Repository openkim/kliff, pull requests merged in 2024-02, with the labels that each got.

#162 Colabfit enhancments by Eric
  kliff/dataset/dataset.py
Labels: fix

#165 Add codecov check for test coverage
  .github/workflows/testing.yml
  setup.py
Labels: enhancement

#164 Added tests for newer modules
  kliff/dataset/dataset.py
  kliff/transforms/configuration_transforms/configuration_transform.py
  kliff/transforms/property_transforms.py
  kliff/utils.py
  setup.py
  tests/dataset/test_ase_parser.py
  tests/dataset/test_configurations.py
  tests/misc/test_utils.py
  tests/test_data/precomputed_numpy_arrays/cm_si.npy
  tests/transformations/test_configuration_transform.py
  tests/transformations/test_descriptors.py
  tests/transformations/test_graphs.py
  tests/transformations/test_property_transforms.py
Labels: fix, enhancement
